document.write ('<section class="td-in-page-banner">\n');
document.write ('  <div class="td-container">\n');
document.write ('    <a href="https://ads.td.com/RealMedia/ads/click_lx.ads/www.td.com/tdct/en/login/L24/1688984379/Middle/TDBank/OTP-Communications_TDCT_EN_Nov2017@OTP-ComingSoon_EW_LI_EN_Feb2018/OTP-Communications_EW_LI_vComingSoon2_EN_c000-02-0313.html/38643755684672506e31594141766833" target="_blank">\n');
document.write ('      <div class="td-row">\n');
document.write ('        <div class="td-col-xs-12 td-col-lg-12 td-banner">\n');
document.write ('          <picture>\n');
document.write ('            <source srcset="https://oasc17.247realmedia.com/RealMedia/ads/Creatives/TDBank/OTP-Communications_TDCT_EN_Nov2017@OTP-ComingSoon_EW_LI_EN_Feb2018/OTPComingSoon_bg_DT_1170x260.jpg" media="(min-width: 1200px)"/>\n');
document.write ('            <source srcset="https://oasc17.247realmedia.com/RealMedia/ads/Creatives/TDBank/OTP-Communications_TDCT_EN_Nov2017@OTP-ComingSoon_EW_LI_EN_Feb2018/OTPComingSoon_bg_DT_1170x260.jpg" media="(min-width: 1024px)"/>\n');
document.write ('            <source srcset="https://oasc17.247realmedia.com/RealMedia/ads/Creatives/TDBank/OTP-Communications_TDCT_EN_Nov2017@OTP-ComingSoon_EW_LI_EN_Feb2018/OTPComingSoon_bg_TL_1024x260.jpg" media="(min-width: 768px)"/>\n');
document.write ('            <source srcset="https://oasc17.247realmedia.com/RealMedia/ads/Creatives/TDBank/OTP-Communications_TDCT_EN_Nov2017@OTP-ComingSoon_EW_LI_EN_Feb2018/OTPComingSoon_bg_MB_640x520.jpg" media="(max-width: 768px)"/>\n');
document.write ('            <!-- Following is fallback for IE. Serve the LG image because we know it');
document.write ("'");
document.write ('s a desktop -->\n');
document.write ('            <img src="https://oasc17.247realmedia.com/RealMedia/ads/Creatives/TDBank/OTP-Communications_TDCT_EN_Nov2017@OTP-ComingSoon_EW_LI_EN_Feb2018/OTPComingSoon_bg_DT_1170x260.jpg" alt=""/>\n');
document.write ('          </picture>\n');
document.write ('        </div>\n');
document.write ('        <div class="td-col-xs-12 td-col-sm-8 td-col-sm-offset-4 td-col-md-7 td-col-md-offset-5 td-banner-content">\n');
document.write ('          <h2>Our new login page is here, and an extra layer of security is coming soon!</h2>\n');
document.write ('          <p class="td-copy-emphasized">\n');
document.write ('            <span class="td-rwd-line">We’ll be replacing security questions with Two-Step Verification, a new way to protect your account.</span>\n');
document.write ('            <!--span class="td-rwd-line">a new way to protect your account.</em> Visa Aeroplan.</span-->\n');
document.write ('          </p>\n');
document.write ('          <div class="td-cta">\n');
document.write ('            <!--button type="button" class="td-button td-button-block td-button-large td-button-transparent td-copy-emphasized">Learn More</button-->\n');
document.write ('			 <button type="button" class="td-button td-button-block td-button-large td-button-clear-green td-copy-emphasized">Learn More</button>\n');
document.write ('          </div>\n');
document.write ('        </div>\n');
document.write ('      </div>\n');
document.write ('    </a>\n');
document.write ('  </div>\n');
document.write ('</section>');
